# Create Simple Neural Network

In [8]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):  # Derivative of sigmoid function
    return x * (1 - x)

training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T

Initialize weights randomly

In [9]:
np.random.seed(1)  # get same random numbers every time

synaptic_weights = 2*np.random.random((3, 1))-1  # 2*[0,1)-1 for 3 rows and 1 column, range is [-1,1]

print(synaptic_weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [11]:
for iteration in range(1000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))

    error = training_outputs - outputs
    adjustments = error * sigmoid_derivative(outputs)

    synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training:')
print(synaptic_weights)

print('Output after training:')
print(outputs)

Synaptic weights after training:
[[ 7.29472383]
 [-0.21601614]
 [-3.43311346]]
Output after training:
[[0.03129247]
 [0.9745453 ]
 [0.97938874]
 [0.02536715]]
