<a href="https://colab.research.google.com/github/Nishitha0730/Machine-Learning/blob/main/TensorFlow%20Basic/TensorFlow_02_quick_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Train model to identify hand written digits

Test TensorFlow Version

In [ ]:
import tensorflow as tf
print("TensorFlow version : ", tf.__version__)

TensorFlow version :  2.18.0


# Load Data Set

In [ ]:
mnist = tf.keras.datasets.mnist  # MNIST dataset consists of 70,000 grayscale images of handwritten digits (0–9), each 28x28 pixels, along with their corresponding labels.
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train , x_test = x_train / 255.0 , x_test / 255.0

# Built a Machine Learning Model

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.08044085, -0.01884616, -0.2058119 , -0.57250905,  0.45234358,
        -0.9568683 ,  0.9121562 , -0.01131985, -0.4857359 , -0.7151256 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09395247, 0.09992138, 0.08288201, 0.05743885, 0.16006397,
        0.03910935, 0.25350565, 0.10067626, 0.06264564, 0.04980444]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(3.2413936)

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# Train and evaluate the model

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8602 - loss: 0.4795
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9564 - loss: 0.1457
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9693 - loss: 0.1030
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9730 - loss: 0.0856
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9779 - loss: 0.0724


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9759 - loss: 0.0819


[0.08190635591745377, 0.9758999943733215]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.83376451e-08, 3.44681546e-08, 2.90492317e-05, 1.40139455e-05,
        8.72831751e-10, 2.03510542e-08, 2.34229892e-11, 9.99953628e-01,
        6.69476776e-08, 3.11569715e-06],
       [2.74368208e-08, 3.80905658e-05, 9.99958873e-01, 1.17289051e-06,
        3.71852864e-16, 5.92121012e-07, 1.08704896e-07, 1.24737756e-15,
        1.13648468e-06, 6.79399977e-14],
       [4.68707924e-07, 9.99071598e-01, 7.73801949e-05, 3.12080629e-05,
        1.09266868e-04, 1.48780246e-05, 5.56855630e-05, 3.10838339e-04,
        3.27241316e-04, 1.36144286e-06],
       [9.99996901e-01, 5.71137471e-10, 7.73974421e-07, 1.85040760e-09,
        2.21146546e-09, 1.59047261e-07, 1.97829104e-06, 1.94214422e-07,
        6.96619368e-12, 4.92159069e-09],
       [1.50763299e-07, 4.65980925e-08, 9.69898429e-06, 1.72757211e-07,
        9.99020100e-01, 2.69105499e-07, 7.05305956e-06, 3.71147471e-05,
        5.79983457e-08, 9.25232947e-04]], dtype=float32)>